### ISSUE TITLE
Colors are mismatched

### ISSUE THREAD

**Issue by Ashish285** [gopalkildoliya/postman-collection-viewer#2]
The sidebar color for POST request is yellow but in the request details, the POST request has blue banner. The colors are exchanged for PUT requests.
![post_yellow](https://user-images.githubusercontent.com/40630962/66914072-a5f7f580-f033-11e9-8038-f5013fd6f593.png)
![put_blue](https://user-images.githubusercontent.com/40630962/66914073-a5f7f580-f033-11e9-86e5-60cf144fdc7f.png)

**Comment by gopalkildoliya** [comment]
Resolved with #3
